# Generated by Django 4.2.30 on 2026-04-22 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('passes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DONE', 'Done')], default='PENDING', max_length=10)),
                ('visited_at', models.DateTimeField(blank=True, null=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='visit_qrcodes/')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.location')),
                ('pass_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='passes.pass')),
            ],
        ),
    ]
